### ISSUE TITLE
I-9 pdf filled form values doesn't display in acrobat XI

### ISSUE THREAD

**Issue by vcyriac** [AckerApple/ack-pdfbox#1]
I used the jar file with the fill argument to fill the form using JSON data.
The resulting pdf is
[i-9-filled.pdf](https://github.com/AckerApple/ack-pdfbox/files/706422/i-9-filled.pdf)
The json data file that I used
[i-9.pdf.json.zip](https://github.com/AckerApple/ack-pdfbox/files/706424/i-9.pdf.json.zip)

When I open the file in Adobe Acrobat XI the field values show up as empty. When I open it in Preview mode the fields show up as filled fields. Suspect that this is an XFA issue

**Comment by AckerApple** [comment]
A basic slack article leads me to think I'd have to do extra coding to support XFA: http://stackoverflow.com/questions/10536334/combining-xfa-with-pdfbox

Currently, only Acroforms are supported.

At this time, unless a pull request is made, I won't be addressing this at the moment. We are filling I9 docs too and it opens in Acrobat DC and Mac preview which is satisfactory for our needs.

Any additional thoughts?

Also, reminder, ack-pdfbox is really a support library for PDFbox-cli-wrap: https://www.npmjs.com/package/pdfbox-cli-wrap

**Comment by AckerApple** [comment]
I'm having another party review. As I've come to learn, Acroforms is the older technology. Appreciate you bringing this issue to my attention. Still uncertain if any immediate action will take place. 

I would think both the field reader and field filler mechanics would both need to be altered.

[The field filler is here](https://github.com/AckerApple/ack-pdfbox/blob/master/ackpdfbox/src/main/java/com/ackpdfbox/app/FieldFiller.java#L69)

[The field reader is here](https://github.com/AckerApple/ack-pdfbox/blob/master/ackpdfbox/src/main/java/com/ackpdfbox/app/FieldReader.java)

**Comment by vcyriac** [comment]
Thank you for your reply.

Yes I stumbled upon the same stackoverflow post, and I reviewed your code a few days ago both the field filler and field reader.

I don't have Acrobat DC at the moment, it seems that Acrobat XI renders the XFA data first even when AcroForms data is present.
My workaround to display the data is to setXFA(null); in your field filler code.

Great work on the pdfbox-cli-wrap.

I agree that no immediate action is necessary and if it is satisfactory for the current needs then let it be.
Once an engineer colleague of mine told me "Don't let perfection get in the way of Good Enough"

**Comment by AckerApple** [comment]
I could make a deeper integration of an option to setXFA(null) if you could pin-point me where you have applied that option to make things work. Please copy/paste github file line link reference.

Much appreciate the feedback on creating the pdfbox-cli-wrap. Being a great dad in my little world is fantastic but I do rather enjoy this next level participation in the big world that is brought to us from open source coding.

**Comment by vcyriac** [comment]
Sure thing
[fieldFiller](https://github.com/fellfromhell/ack-pdfbox/blob/xfa-null/ackpdfbox/src/main/java/com/ackpdfbox/app/FieldFiller.java)

**Comment by AckerApple** [comment]
Any reason for the flatten, as seen here:
[file link](https://github.com/fellfromhell/ack-pdfbox/blob/faa2c9b67d92099b3e4c2b1e70a5102fd35f8ae8/ackpdfbox/src/main/java/com/ackpdfbox/app/FieldFiller.java#L106)

We could add an option to flatten but I am curious does NOT flattening affect the XFA fix?

**Comment by vcyriac** [comment]
Flattening or Not Flattening does not affect the XFA fix.

My reasoning was, lets say we capture the data into I-9 form digitally, flattening the PDF removes the blue highlighted form fields, and gives the PDF a finalized look, so any future user is not tempted to change or Edit any form fields after opening the file.

Another step would be to sign and lock the document. Which you already have

**Comment by AckerApple** [comment]
Great. I'll add a flatten option default false and I'm going to enforce XFA null just as you have it (not going to make XFA an option).

I will report

**Comment by AckerApple** [comment]
Alright. Done.

Please review. I await your overview to update the pdfbox-cli-wrap package that depends on ack-pdfbox.

Fix is in version 1.2.4

**Comment by vcyriac** [comment]
Reviewed and commented. That was pretty fast.

With your permission, can I close this issue?

**Comment by AckerApple** [comment]
It is preferred that you close this issue (although bug reports often spell popularity but seriously, close it).

Also, in my opinion, we should all reply to issues as quickly as possible and try to remain prompt in responses to keep this open source thing thriving. In the past, in enterprise software, we all felt pretty hopeless when met with a proprietary bug (that bologna has a first name and it's A D O B E).

**Comment by vcyriac** [comment]
I agree all software should be open source, I think it comes from the Richard Stallman school of thought

**Comment by AckerApple** [comment]
Hey good guy. Looking for help. The new 2017 I-9 is unreadable to almost every reader EXCEPT Adobe Acrobat. Can't view in Mac Preview, and can't preview in browser.

https://www.uscis.gov/system/files_force/files/form/i-9.pdf?download=1

Any thoughts? Frantically googling. Can't read the dern document even using paid software.

**Comment by vcyriac** [comment]
Hi Acker,
 It seems that this pdf has new features and is a dynamic XFA document.

Here are some helpful links, however I'm sure you must have read them all
https://forums.adobe.com/thread/866262
https://www.experts-exchange.com/questions/28938740/PDF-File-Not-Opening-in-Chrome-Browser.html

The spanish version of the i-9 form opens up fine.

Currently there is no software besides adobe acrobat that opens up the form
on a Mac.

The option that I see is to use the paper form
https://www.uscis.gov/system/files_force/files/form/i-9-paper-version.pdf?download=1

Manually recreate the form fields, you will lose the QR code functionality.

**Comment by AckerApple** [comment]
I went down the same path and came to the same conclusion: Download paper version and re-add fields. We have not yet done this as we are awaiting for more superior overview of the situation at hand. I quite imagine that if we do recreate the I9 fields, I'll push for us to post on GITHUB.
